Use broadcastAsyncMessage instead of sendAsyncMessage
Use broadcastAsyncMessage instead of sendAsyncMessage, fixing this error:

Error: TypeError: window.messageManager.sendAsyncMessage is not a function
Source File: chrome://multipletab/content/multipletab.js
Line: 1152

Doc: https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/The_message_manager#Chrome_to_content